### PR TITLE
Lumberjack-x2 update board shape

### PR DESCRIPTION
**Pull request by mangkoran**
First of all, thank you for making this modification to Lumberjack. I was in search for GH60-compatible ortho, and then I found you repo. I couldn't be more happier. I am no expert (even playing with) KiCAD or PCB making before, so if you found any mistakes/errors, please let me know!

In this PR I tried to fix several errors when trying to open the project in KiCAD 6:

1. Board shape: I incorporate separate board shape SVG to ease future change.
2. Misplaced mounting holes: In the attachment below, I found that hole H5 and H6 are (possibly) misplaced. By looking at the footprint and the finished PCB you have released, I think that H5 and H6 could be removed. I merge the side mounting holes with the board shape. I also remove the "hole footprint" as it produce error too. I don't really know what is the purpose of this footprint so if it should be there, let me know!
3. Minor clean up: I try to suppress as many warning as I could (unconnected paths, path's hole clearance, etc.)

Misplaced H5 and H6
image
Hole footprint.. (head branch)
image
..removed (this PR)
image

### CODE REVIEW

**Comment by rgoulter** [comment]
Thank you for the PR, and I'm glad you like the idea.

I'm currently traveling for Lunar new year. I'll be able to take a better look at this PR after a week or so.

> Board shape: I incorporate separate board shape SVG to ease future change.

This is a good idea, thanks.

> Misplaced mounting holes: In the attachment below, I found that hole H5 and H6 are (possibly) misplaced. By looking at the footprint and the finished PCB you have released, I think that H5 and H6 could be removed. I merge the side mounting holes with the board shape.

Weird. That extra hole doesn't show up in the gerbers, but does show up like in your screenshots on the interactive BOM.

To remind myself: per the schematics: H1-H3 designate holes for the mounting case, and H4-H7 were for the holes for mounting the acrylic cover over the microcontroller area.

Yeah, that misplaced H5/H6 definitely shouldn't be as it is in your screenshots.

> I also remove the "hole footprint" as it produce error too. I don't really know what is the purpose of this footprint so if it should be there, let me know!

The intention for these is cosmetic. Some GH60-compatible PCBs include the copper (& remove soldermask).

When I'd used just an unconnected PTH (like in the original GH60 PCB design; and IIRC in peej's lumberjack), JLCPCB was fine with this but another PCB fabrication manufacturer asked me to remove that (since it'd require drilling outside the board outline).

What's there on master branch now was my attempt at getting the same effect.

>  Minor clean up: I try to suppress as many warning as I could (unconnected paths, path's hole clearance, etc.)

Thanks

**Comment by mangkoran** [comment]
Thank you for your response! I am trying to add commits to improve the appearance (track path for now). I'll let you know if this PR is ready to merge.

Until then, enjoy your vacation!

**Comment by mangkoran** [comment]
Are these tracks necessary?

image

**Comment by mangkoran** [comment]
While I'm at it, I also tried to move the MCU down so that the USB port could be used. I haven't pushed it. If you think is it any good, I will push it.

image

**Comment by rgoulter** [comment]
> Are these tracks necessary?

I put them there to ensure the GND pads of the USB connector connect to the GND plane. (Feel free to remove them so long as the filled zone connects to those pads).

> While I'm at it, I also tried to move the MCU down so that the USB port could be used. I haven't pushed it. If you think is it any good, I will push it.

Note that the capacitors should be placed close in the circuit to the power pads of the LEDs. IIUC, these serve as "decoupling capacitors", which reduces noise in the circuit. -- Although I'll acknowledge that how the capacitors are arranged in rev2021.1 is more "artistic" than adhering to this.

Also, just judging by the screenshot, I'd stick to the thicker traces for 5V for the RGB LEDs.

In terms of placement of the devboard and the LEDs:

* I think in rev2021.1, it's maybe unpleasant there's more space below the LEDs than above.

* TBH, my initial impression was that I don't like the idea.
  * I think the devboard sits high enough that it might block out views of the components; and maybe a connected cable would too.
  * While the placement of the devboard in rev2021.1 certainly doesn't allow placing the cable with standard GH-60 cases.. it's possible to use the devboard's USB with a custom case or (with the cheap GH-60 cases) dremeling it out.
  * It would be finicky to insert a USB cable with the devboard placed like that.
  * In terms of placement of the devboard: the bluepills' SWD header is typically already soldered; with the devboard that low, it may cover the diodes, but may also be a bit annoying to access.

* Though, what I like about the idea:
  * It's more practical. If the USB connector on the keyboard PCB breaks off, it'd at least provide some option of using the PCB.
  * Arguably, having the devboard "in the middle" might look nicer than as it is now.
  * Status LEDs are usually at the top of the keyboard. The LEDs in the lumberjack PCB are at the top of the PCB.
  * Even if maybe it's not practical to use the devboard's USB connector when using standard GH-60 cases, it's in the spirit of this repository to give the design a try.

I'd ask to first limit the scope of this PR to fixing the PCB design for Kicad 6, with minimal changes. (Fixing the board shape, removing the weird extra hole module, tidying up warnings).

This additional change (of moving the devboard and LEDs around) can be done in a separate/later PR.

**Comment by mangkoran** [comment]
Alright, thank you for your response! I will make a separate PR for the MCU moving.

**Comment by rgoulter** [comment]
> Sorry for the delay. ... You may review it whenever you are free. 

Sure. Something's only fun if you don't have to be relied on for it.

> Also how to generate PCB render like in README?
> So that you (or anyone) could just see the updated PCB for quick look at what I've changed.

I've written a [kibot](https://github.com/INTI-CMNB/KiBot) config file (`pcb/config.kibot.yaml`).
In theory, all this takes is running `kibot -b <path to .kicad_pcb file>`, and it will
generate the output assets like a zip of the gerber files, or the nice pcbdraw renders.

I think it's a bit more difficult with the mix of Kicad 5 and Kicad 6.
(It's not smooth running Kicad 6 against Kicad 5 files).

The 'difficult' part is getting Kibot and all its dependencies.

Personally, I use [nix](https://nixos.org/) as an easy way to get kibot installed on Linux.
(Though, I haven't tried using the nix files I wrote on a Linux outside of NixOS). So I'd run
`nix develop .#kibot-kicad5-nixos`, then `cd pcb` and `kibot ...` as above.

Using Docker might be simpler in other cases.
Kibot's official Docker image is [setsoft/kicad_auto](https://hub.docker.com/r/setsoft/kicad_auto).
I bundled a Docker image at [richardgoulter/kibot](https://hub.docker.com/repository/docker/richardgoulter/kibot/).
-- This would involve a `docker run` command, as documented in the DockerHub pages.

### Feedback

- Wonderful! There are no design rule checking errors. :D

- Bump the revision rev2021.2:
  (In the schematic and the kicad_pcb, and in the silkscreen on the PCB.
   You can put your name or your github username as the author if you're
   comfortable doing so; I'm fine if it's left blank, or if it remains
   my name).
  Hopefully there's actually no significant difference, but I want to
  be able to easily distinguish between PCBs fabricated from the Kicad 5
  source (rev2021.1) vs this new one.

- The 0.2mm GND trace near J1: I'd be more comfortable if the GND trace was 0.5mm
  (i.e. the net class' width) when connecting J1's GND pads to the
  copper plane.

x2_pr2_gnd_traces

- Avoid right-angles in traces: Right angles are more 'fragile' than
  45-degree angles, since there's less overlap of the copper.

x2_pr2_right_angle_traces

- Lumberjack.pretty - The other footprint libraries are checked in
  as Git submodules, this should be too.

- The 'mounting hole slot':
  I know this approach is how the Lumberjack PCB and GH-60 PCB do it.
  And JLCPCB is fine with the gerbers made this way.
  But, I've had problems sending it to a fabrication house which didn't
  like that the drill hole is outside the board outline.
  That's why I had mounting hole slot as part of the edge.cuts in
  rev2021.1.
  - Also why I tried to approximate the "PTH" by using a footprint
    with copper+soldermask in the `Graphic_Mask_HalfHole` module.
    I haven't tried, but I'm guessing there's a DRC warning for that,
    though?

x2_pr2_drl_outside_board_outline

- The Open-Source Hardware logo:
  I had put it on the silkscreen.
  In the lumberjack PCB, it's on the soldermask layer (as is the version info etc.).
  Do you not like it? I think it was kinda neat,
  though I don't mind if it's with copper or soldermask or on the silkscreen.

**Comment by mangkoran** [comment]
Hello Richard. Apologize for the late reply. Since then, I have been busy with my study (sigh) and I could not continue to improvise this PR. I also tried to design my own keeb PCB which suits me more. Feel free to close this PR. Have a good day!

**Comment by rgoulter** [comment]
Ah, no worries. :)
 
Thanks for the feedback you gave in this PR. Have fun with your keyboard PCB designing. :)

**Pull request closed without merging**
